---
- hosts: localhost
  tasks:
  - name: gather facts and store them to a register
    ec2_instance_facts:
      filters:
       "tag:Name": "demo-ansible"
    register: server
  - debug:
      msg: "{{ server.instances[item].public_ip_address }}" 
    with_items:
      - 0
      - 1
  #- name: saving public ip
  #  lineinfile:
  #    dest: ~/hosts
  #    insertafter: "[DEVSERVERS]"
  #    line: "{{ item.public_ip_address }}"
  #    state: present
  #  with_items: server.instances
   # become: yes
   # become_method: sudo
