---
#- hosts: DEVSERVERS
#  gather_facts: no
#  tasks:
#  - name: update 
#    raw: sudo apt -y update   
#    args:
#      executable: /bin/bash
#  - name: install python 
#    raw: sudo apt -y install python-minimal 
#    args:
#      executable: /bin/bash

- hosts: DEVSERVERS
  vars_files:
    - ./vars.yml 
  roles:
    - {
        role: nvm        
      }

- hosts: DEVSERVERS
  gather_facts: no
  become: yes
  vars_files:
    - ./vars.yml 
  roles:
    - {
        role: base
      }
      
#- hosts: DEVSERVERS
#  vars:
#    hashcloud_server_testing_privatekeypath: ~/.ssh/hashcloud-server-testing-private
#  roles:
#   - {
#        role: main
#     }
