---
- hosts: DEVSERVERS
  vars_files:
    - ./vars.yml 
  become: yes
  roles:
    - {
        role: nvm        
      }

- hosts: DEVSERVERS
  gather_facts: no
  become: yes
  vars_files:
    - ./vars.yml 
  roles:
    - {
        role: base
      }
