## this is dummy file created for testing
---
- name: copy ssh private key
  copy: 
    src: "{{ privateKeySourcepath }}"
    dest: "{{ privateKeyDestinationpath }}"
    mode: 0600    

#- name: Cloning hashcloud-infra repository
#  git:
#    repo: "{{ hashcloudInfraRepository }}" 
#    dest: "{{ hashcloudInfraRepoDestPath }}"
#    accept_hostkey: yes
#    key_file: "{{ hashcloud_server_testing_privatekeypath }}"

- name: Clone the hashcloud-webapp repository
  git:
    repo: "{{ hashcloudWebAppRepository }}"
    dest: "{{ hashcloudWebAppRepositoryDest }}"
    accept_hostkey: yes
    key_file: "{{ hashcloud_server_testing_privatekeypath }}"

- name: Cloning the secrets repository
  git:
    repo: "{{ hashcloudWebAppSecretsRepository }}"
    dest: "{{ hashcloudWebAppSecretsRepoDest }}"
    accept_hostkey: yes
    key_file: "{{ hashcloud_server_testing_privatekeypath }}"

- name: Running the Node Server in the background
  shell: npm  install
  args:
    chdir: ~/hashcloud-webapp

- name: Running the Node Server in the background
  shell: |
    screen -dm -S NODESERVER npm run server
  args:
    chdir: ~/hashcloud-webapp