#- name: make sure ssh is running
#  shell: eval $(ssh-agent -s)
#- name: loading ssh private key
#  shell: ssh-add ~/.ssh/{{ private_key_name }}
- name: copy ssh private key
  copy: 
    src: "{{ privateKeySourcepath }}"
    dest: "{{ privateKeyDestinationpath }}"
    mode: 0600
- name: Cloning hashcloud-infra repository
  git:
    repo: "{{ hashcloudInfraRepository }}" 
    dest: "{{ hashcloudInfraRepoDestPath }}"
    accept_hostkey: yes
    key_file: "{{ hashcloud_server_testing_privatekeypath }}"
- name: cloneing pyhashcloud-processor repository
  git:
    repo: "{{ pyhashcloudProcessorRepository }}"
    dest: "{{ pyhashcloudProcessorRepoDestPath }}"
    accept_hostkey: yes
    key_file: "{{ hashcloud_server_testing_privatekeypath }}"
- name: Cloning the secrets repositor
  git:
    repo: "{{ pyhashcloudProcessorSecretsRepo }}"
    dest: "{{ pyhashcloudProcessorSecretsRepoDest }}"
    accept_hostkey: yes
    key_file: "{{ hashcloud_server_testing_privatekeypath }}"
- name: install the requirements
  pip:
    requirements: ~/pyhashcloud-processor/requirements.txt
- name: Python Cloud Creator Under Progress and Running the Python Cloud Deletor in background
  shell: | 
    cd pyhashcloud-processor 
    screen -dm -S PYTHONNETCREATOR python3 netCreator.py production
    screen -dm -S PYTHONNETDELETOR python3 netDeleter.py production
- name: Clone the hashcloud-webapp repository
  git:
    repo: "{{ hashcloudWebAppRepository }}"
    dest: "{{ hashcloudWebAppRepositoryDest }}"
    accept_hostkey: yes
    key_file: "{{ hashcloud_server_testing_privatekeypath }}"
##
#- name: check command module to run npm install
#  command: npm install
#  become_user: ubuntu
#  args:
#    chdir: /home/ubuntu/hashcloud-webapp/

- name: Installing application required npm modules
  shell: npm install
  become_user: ubuntu
  args:
    chdir: ~/hashcloud-webapp/
    executable: /bin/bash

#- name: Install packages based on package.json.
#  npm:
#    path: ~/hashcloud-webapp/
  
- name: Cloning the secrets repository
  git:
    repo: "{{ hashcloudWebAppSecretsRepository }}"
    dest: "{{ hashcloudWebAppSecretsRepoDest }}"
    accept_hostkey: yes
    key_file: "{{ hashcloud_server_testing_privatekeypath }}"
- name: Running the Node Server in the background
  shell: |
    cd ~/hashcloud-webapp
    screen -dm -S NODESERVER npm run server
- name: Generating the RSA keys with fd name
  shell: |
    cd ~/.ssh
    ssh-keygen -t rsa -f fd -P ""
    cat ~/.ssh/fd.pub >> ~/.ssh/authorized_keys
    cd ~
