## copies required ssh key into server to download git repositories 
- name: copy ssh private key
  copy: 
    src: "{{ privateKeySourcepath }}"
    dest: "{{ privateKeyDestinationpath }}"
    mode: 0600
## dowloads hashcloud-infra repository from git
- name: Cloning hashcloud-infra repository
  git:
    repo: "git@github.com:HashCorpIO/{{item.repo}}.git" 
    dest: "{{ item.dest }}"
    accept_hostkey: yes
    key_file: "{{ hashcloud_server_testing_privatekeypath }}"
  with_items: "{{gitRepos}}"  
# here pip module with pip3 executable
## installs requirements and launchs screens for netCreator.py and netDeleter.
- name: Python Cloud Creator Under Progress and Running the Python Cloud Deletor in background
  shell: | 
    pip3 install -r requirements.txt
    sleep 2 
    screen -dm -S PYTHONNETCREATOR python3 netCreator.py production
    sleep 2
    screen -dm -S PYTHONNETDELETOR python3 netDeleter.py production
  args:
    chdir: ~/pyhashcloud-processor
# downloading packages from package.json
# problem here , npm install not working this code
- name: Running the Node Server in the background
  shell: "npm install"
  args:
    chdir: ~/hashcloud-webapp
# problem here in this code

# dowloads required packages from package.json and launches NODESERVER

- name: Running the Node Server in the background
  shell: "screen -dm -S NODESERVER npm run server"
  args:
    chdir: ~/hashcloud-webapp

# generetes rsa keys 

- name: Generating the RSA keys with fd name
  shell: |
    ssh-keygen -t rsa -f fd -P ""
    cat ~/.ssh/fd.pub >> ~/.ssh/authorized_keys
  args:
    chdir: ~/.ssh
    creates: ~/authorizedkeyscreated.txt