- name: installing nvm  
  shell: >
    curl https://raw.githubusercontent.com/creationix/nvm/v0.34.0/install.sh | sh
    creates=/home/{{ ansible_user_id }}/.nvm/nvm.sh
- name: Install node and set version
  shell: >
    /bin/bash -c "source ~/.nvm/nvm.sh && nvm install 8.15.1 && nvm alias default 8.15.1"
    creates=/home/{{ ansible_user_id }}/.nvm/alias