- name: check for os version
  apt_repository:
    repo: "{{ item }}"
    update_cache: yes
    state: present
  with_items: "{{ reposRequired }}"

- name: installing dependencies
  apt:
    name: "{{ dependencies }}"
    state: present
- name: installing packages
  apt:
    name: "{{ packages }}"
    state: present