# tasks file for instance 
# launches an instance check vars.yml file for changeing specs of the instance
---
- name: lunch an server
  ec2:
    key_name: "{{ keyName }}"
    region: "{{ instanceRegion }}"
    instance_type: "{{ instanceType }}"
    image: "{{ imageId }}"
    wait: yes
    count: "{{ instanceCount }}"
    vpc_subnet_id: "{{ vpcSubnetId }}"
    assign_public_ip: yes
    instance_tags:
      Name: "{{ instanceName }}"
    group_id: "{{ sgId }}"
    user_data: |
               #!/bin/bash
               sudo apt-get update
               sudo apt-get install python-minimal -y
  register: ec2
  tags: ec2

# if you want to debug the ec2 variables uncomment following two lines
#- debug:
#    var: ec2
 
# if hosts file exits already, deletes it

- name: delete hosts file if already present 
  file:
    path: "{{ hostFilePath }}"
    state: absent

# creates an new hosts file 

- name: creating a file, with all the servers list that are created by ec2 instance
  lineinfile: 
    path: "{{ hostFilePath }}"
    line: '[DEVSERVERS]'
    create: yes

# saves ip of newly launched into hosts file

- name: saving public ip of first host
  lineinfile: 
    dest: "{{ hostFilePath  }}"
    insertafter: "[DEVSERVERS]"
    line: "{{ ec2.instances[0].public_ip }}"
    state: present

# waits for ssh get started on the server

- name: wait for ssh
  wait_for:
    host: "{{ ec2.instances[0].public_ip }}"
    port: 22
    search_regex: OpenSSH
    delay: 10
    state: started
  connection: local
