# tasks file for instance
---
- name: lunch an server
  ec2:
    key_name: "{{ keyname }}"
    region: "{{instance_region}}"
    instance_type: "{{ instanceType }}"
    image: "{{ imageId }}"
    wait: yes
    count: "{{ instancecount }}"
    vpc_subnet_id: "{{ VpcSubnetId }}"
    assign_public_ip: yes
    instance_tags:
      Name: "{{ instanceName }}"
    group_id: "{{ SgId }}"
    user_data: |
               #!/bin/bash
               sudo apt-get update
               sudo apt-get install python-minimal -y
               python --version
  register: ec2
  tags: ec2
- debug:
    var: ec2
  
 
#- name: gather facts and store them to a register
#  ec2_instance_facts:
#    filters:
#      "tag:Name": "testing_ansible"
#  register: server
- name: delete hosts file if already present 
  file:
    path: "{{ HostFilePath }}"
    state: absent
    
- name: creating a file, with all the servers list that are created by ec2 instance
  lineinfile: 
    path: "{{ HostFilePath }}"
    line: '[DEVSERVERS]'
    create: yes
    
- name: saving public ip of first host
  lineinfile: 
    dest: "{{ HostFilePath  }}"
    insertafter: "[DEVSERVERS]"
    line: "{{ ec2.instances[0].public_ip }}"
    state: present

- name: wait for ssh
  wait_for:
    host: "{{ ec2.instances[0].public_ip }}"
    port: 22
    search_regex: OpenSSH
    delay: 10
    state: started
  connection: local
  

#  become: yes
  
#- name: saving public ip of second host
#  lineinfile: 
#    dest: ~/hosts
#    insertafter: "[DEVSERVERS]" 
#    line: "{{ ec2.instances[1].public_ip }}"
#    state: present
#  
#- name: saving public ip
#  lineinfile: 
#    dest: ~/hosts
#    insertafter: "[DEVSERVERS]" 
#    #line: '{{ ec2.instances[ + {{ item }} + ].public_ip }}'
#    #line: "{{ 'ec2.instances[' + '{{ item }}' + '].public_ip'}}"
#    line: "{{ ec2.instances[item].public_ip }}"
#    state: present
#  with_sequence:  count=2
#- name: add host to inventory file
#  add_host:
#    name: "{{ ec2.instances[0].public_ip }}"
#    groups: DEVSERVERS
#    inventory_dir: /home/ubuntu/ansibleaws/hosts